### ISSUE TITLE
Module keeps "Loading" forever

### ISSUE THREAD

**Issue by cyberdie** [Tuxdiver/MMM-Rest#1]
The configured URL resolves correctly using curl and gives back the required info (temperatur from an aquarium).
```javascript
{
        module: 'MMM-Rest',
        position: 'bottom_right',               // This can be any of the regions.
                config: {
               debug: true,
            sections: [
                {
                    suffix: 'ºC',
                    digits: 1,
                    url: 'http://192.168.1.4:8000/devices/temp2/sensor/temperature/c'
                },
            ],
            output: [
                ['Temperatura Acuario','@1']
            ],
                }
},
```

**Comment by Tuxdiver** [comment]
I think I found the problem: getting values from another server than the mirror server is not allowed. The "same-origin-policy" of JavaScript does not permit to call other servers. 

So at the moment, it is not really possible to use the module. I will try to change it to use a node helper for getting the data, but I can't tell you, when it will be ready.

**Comment by cyberdie** [comment]
Have you see this one: https://github.com/Eunanibus/MMM-HTTPRequestDisplay

**Comment by Tuxdiver** [comment]
I looked at MMM-HTTPRequestDisplay, but I think, it must have the same problem with foreign remote URLs.

I just added a node_helper.js to my module. Could you please try again?

**Comment by cyberdie** [comment]
Git Pull, reboot and IT WORKS!
Thanks @Tuxdiver !!
