### ISSUE TITLE
PR request or Fork?

### ISSUE THREAD

**Issue by dathbe** [Tuxdiver/MMM-Rest#10]
I solved the multiple instances issues by passing a unique id through the update notifications.  I can either create a PR for you to add this into your module, or I can create a new fork module called "Rest2".  Your call.

**Comment by Tuxdiver** [comment]
A fork will of course work, but I don't think it's a good idea, because users will be confused which module to use. So please create a PR and I will merge it.

**Comment by dathbe** [comment]
No problem.  You just said you were trying to get out of the maintaining business.  Give me a bit of time and I'll create a PR.

**Comment by dathbe** [comment]
See #11

**Comment by Tuxdiver** [comment]
Thanks a lot for your PR, it is merged
