### ISSUE TITLE
Better cell alignment?

### ISSUE THREAD

**Issue by dathbe** [Tuxdiver/MMM-Rest#18]
I made another change, which addresses how cells are aligned.  As I understand the current code, if the cell contains an '@' section id variable, it will align the cell to the right, otherwise it will align the cell to the left.  This works well when the row is of the format [description, variable].  But if the use case calls for [variable, description] (e.g., "5 bananas"), or [variable, variable] (my use case because the description changes based on some factors), the alignment isn't right.  I THINK it makes more sense have left columns aligned left, and right columns aligned right, so I've made a change to do that here:
https://github.com/dathbe/MMM-Rest/tree/patch-1
I will create a PR if you think this is an improvement.

**Comment by Tuxdiver** [comment]
I don't know, if that may break other users setup. Maybe we could add the alignment somehow different?

Maybe another optional array with the same  number of rows as the "output" one:
```
output_align: [
  'lrr',
  'lr',
  'rr',
  'cc',  // center
]
```
or simpler, just a:
```
default_output_align: 'lrrrrr'
```
which then produces the alignment you wanted and uses the old behavior if not set.

**Comment by dathbe** [comment]
What is we just make a binary true/false variable on whether you want the current behavior or my new proposed behavior?  Default would be existing. I feel like the arrays are complicated enough as they are.

**Comment by Tuxdiver** [comment]
Yes, that is the easier solution - you are right, the data structure is complicated enough...
I would really appreciate a PR for that.
If you like, you may also edit the "Changelog" in README.md  and put your name to the changes, you proposed / did.
