### ISSUE TITLE
Display strings?

### ISSUE THREAD

**Issue by mueller-ma** [Tuxdiver/MMM-Rest#3]
Hi,
is it possible to display strings and to "translate" them?

e.g. OpenHAB gives me "OPEN" or "CLOSED" via rest api, but mmm-rest displays "NaN". It would be great, if the addon could handle simple word replacement (e.g. "OPEN" => "geöffnet")

**Comment by Tuxdiver** [comment]
Currently it only supports floating point / integer values, but it's an cool idea - I will have a look at it!

**Comment by Tuxdiver** [comment]
Please try the current version, I added a format string and a mapping possibility.

**Comment by mueller-ma** [comment]
Great feature, but two problems:
I removed to dir MMM-Rest, did git clone... and npm install.
I got this warning: `npm WARN package.json magic-mirror-module-rest@1.0.0 No repository field.`
I don't know if this is something.

The other problem is more important. I am not able to display some data in my mirror. Even with your config it only displays `...` instead of data.

**Comment by Tuxdiver** [comment]
Will have a look at the npm problem later - the other one is fixed now (I hope)

Sorry for the bug - should have tested it better :-(

**Comment by Tuxdiver** [comment]
The problem with the npm install warning is fixed, thanks for reporting it!
