### ISSUE TITLE
Node-red connection

### ISSUE THREAD

**Issue by marksev1** [Tuxdiver/MMM-Rest#5]
So I'd like to display my sensor values from home-assistant or node-red (I get them via MQTT btw) on a magic mirror....

I have several questions, first, can I display multiple values or just 3 like in the example?

Second, how do I need to construct the url so that this module will pick it up and display it? Is it a http post request or what is it? 

So does this code just display the numbers or string that it gets at the end of this field -> ?text=

**Comment by Tuxdiver** [comment]
You can have as much values as you like, just add more "sections" and then define the "output" table.
The request is a simple "GET" request, expecting one value of plain text output with any HTML or XML or JSON or ...

I am using openHAB, which stores the last values in its internal variables and the API of openHAB gives these values back to the mirror.
This is the URL I use for openHAB: `http://192.168.178.5:8090/rest/items/wohnzimmer_humidity/state`

In node-red it should be possible to create a flow with a 'http'-node, set 'msg.payload' to the value you need and give it to a 'http-response'-node. 

I don't know, if home-assistant has any API.

**Comment by marksev1** [comment]
I can push home-assistant stuff via mqtt to node-red and then forward to magic mirror :)...Awesome! Thanks this looks like a good explanation. Thanks!

**Comment by marksev1** [comment]
Actually can you explain this part : "The request is a simple "GET" request, expecting one value of plain text output with any HTML or XML or JSON or ..." 

In more detail.  So I need to send a json to it? How does it need to look like?

**Comment by Tuxdiver** [comment]
Attention: the values can't be pushed to the mirror, it will fetch them. So node-red has to store them somewhere (flow,global), wait for the GET request and then pick them from (flow,global) again and return them via http-response, but that should be possible.
So the flow should have two parts:
mqtt (from HA) -> change(payload -> flow.sensorXX)
http -> change(flow.sensorXX -> payload) -> http-response

**Comment by marksev1** [comment]
Just a comment, would be super nice if there was a MMM-MQTT with the same functionality that this one has.
