### ISSUE TITLE
Still working for OpenHAB?

### ISSUE THREAD

**Issue by dathbe** [Tuxdiver/MMM-Rest#8]
Is this still working for OpenHAB?  I suspect this was built and last updated before OH added authorization, and I'm not getting reliable connections without passing an authorization header.  I'm curiously getting only sporadic values returned, with most of my entries showing "..." most of the time.  Though which entries show "..." changes.

**Comment by Tuxdiver** [comment]
I don't use OpenHAB for some time anymore, so if they added authorization, I am sure, it will probably not work anymore. If you can't send the credentials in the URL, like http://username;password@host/, the plugin will not work.

The fact, that you get some values but not all and always changing results is strange - maybe there is some kind of maximum requests per second from one IP in OpenHAB?

**Comment by dathbe** [comment]
Thanks for the follow-up.  I don't think there's a limit.  I make multiple successive calls with python scripts all the time.  I'm new to MagicMirror, but it seems your module is still the best for OH integration.  So I might have to code my own.

**Comment by dathbe** [comment]
For anyone running into the same issue I was having, it appears to have been a problem with trying to format the response as ```%d``` when it wanted ```%s```.  If I'm guessing, messing this up with one item did just enough damage that it gave inconsistent results with the other items.  It turns out that, even though OH takes authorization now, the read-only rest API is still accessible without credentials.
