### ISSUE TITLE
Second Module?

### ISSUE THREAD

**Issue by dathbe** [Tuxdiver/MMM-Rest#9]
Is it possible to add a second MMM-Rest module in a config?  I'm struggling to make it work, and I think it has to do with the fact that, in the second module, when you declare the ```output``` in the second instance as, say ```@1```, it looks to the ```sections``` from the _first_ instance for the data.  But using ```@2``` (one beyond the number in the first instance) results in null.

Update:  I've gotten it to work (I think) by duplicating the ENTIRE ```mappings``` and ```sections``` sections in the second instance, and changing only the ```output```.  But this is obviously pretty cluttered and requires careful tracking to make sure they stay consistent.  So if there's a more elegant solution, I'd love to know.

**Comment by Tuxdiver** [comment]
I don't think, there is an easy solution for that and I think adding a second module stores the information in the same datastructure as the first one. So strange things may happen...

The module is more or less abandoned, so please don't expect a working version... If someone else wants to take the ownership of this module, just get in contact with me

**Comment by dathbe** [comment]
If it stops working, or I get a hankering to implement some tweaks, I might fork it and post on the 3rd-party modules page.
Thanks for doing the hard work of getting it set up initially.
